### ISSUE TITLE
Can't Mint Card

### ISSUE THREAD

**Issue by sshivaditya2019** [ubiquity-os/permit-generation#101]
I'm having trouble minting a card. I keep getting the error: "The reward has already been claimed by the user." This might be caused by a CORS issue or a problem fetching the IP. I can add logs if that would help.

**Comment by 0x4007** [comment]
@rndquu 

Although perhaps this should be in pay.ubq.fi

**Comment by Keyrxng** [comment]
@sshivaditya2019 

1. When was the permit generated?
2. Are you using a VPN or anything?
3. The cards feature would attempt to verify a txhash as far as I know, did your logs contain anything like that?

I guess it didn't get that far and is likely an invalid permit if it's more than a couple weeks old.

Sharing logs is always a good idea though

**Comment by Keyrxng** [comment]
> It was generated last week.

Likely rules out the issue with permits stemming from `permit-generation` a few weeks ago.

> I don’t see any mention of a txhash in the logs.

> I'm not sure what happened. I can see the contract call on GnosisScan, but after that, I started receiving the message: "The reward has already been claimed by the user."

Share this info with us dude. explorer, permit etc so we can see on chain what's happening. By the sounds of it the permit was claimed but not 100% without on-chain evidence, that's really the only way to investigate.

Rndquu and EresDev know more about the cards feature than I do but they'd need the infos I've asked for.

**Comment by Keyrxng** [comment]
So the permit was claimed and it looks like it's been claimed correctly to the treasury address as expected, eresdev will probs know more he wrote that feature and he'd likely be the one to resolve the issue, I'll message them on TG to check this issue

**Comment by Keyrxng** [comment]
> Although perhaps this should be in pay.ubq.fi

This should be transferred

**Comment by EresDev** [comment]
First, @0x4007 needs to check if there is sufficient balance at Reloadly. 

After this, your mint request has already partially failed and it is something being addressed in https://github.com/ubiquity/pay.ubq.fi/issues/291. The current solution is manual. I can retry manually for you. I already can see the tx hash above. I need to know the country you are minting card from so that you get suitable card. 

And just to confirm, do you remember what card were you offered? Was it "Virtual MasterCard International USD US" ?

**Comment by 0x4007** [comment]
![image](https://github.com/user-attachments/assets/5bf87ac2-ef89-43cc-96b1-e1035eb13c4d)

Surely I'm not the only one to be able to login and fix this problem. Half of you guys have admin accounts I thought. What do I need to do and why can't you guys fix this without depending on me to?

**Comment by EresDev** [comment]
Hi @rndquu the proxy appears to be having issues. Can you look into it? 
![image](https://github.com/user-attachments/assets/bec4c603-8cee-4e86-9d0d-5801cd1a4e0a)

**Comment by rndquu** [comment]
@EresDev 

> First, `0x4007` needs to check if there is sufficient balance at Reloadly.

It's sufficient, ~$1k

> Hi @rndquu the proxy appears to be having issues. Can you look into it? 

The proxy works fine, I've whitelisted only cloudflare ips to able to call https://web3-gateway-test.com/proxy/reloadly/production/ because my VPS was heavily DOSes right after [this](https://github.com/ubiquity/pay.ubq.fi/pull/352) PR. I will move proxy URL to env variable and share with you for testing purposes.

The original issue should be solved in https://github.com/ubiquity/pay.ubq.fi/issues/291. Meanwhile @EresDev could you mint the gift card manually for @sshivaditya2019?

**Comment by EresDev** [comment]
@sshivaditya2019 I have minted a card for you. You can get redeem codes from your permit URL.

**Comment by rndquu** [comment]
@EresDev DMed you in telegram reloadly proxy URL for testing purposes
