### ISSUE TITLE
Downgrade to `Ethers@v5` 

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os/permit-generation#60]
This repo I think is the only one which is using `Ethers@v6` and it would be best if the package was downgraded and any affected logic be refactored to work with `V5`

**Comment by CaptainPrinz** [comment]
i really cant figure out why its failing

**Comment by 0x4007** [comment]
> /start

@gentlementlegen  another start failure

**Comment by gentlementlegen** [comment]
@Keyrxng rfc

**Comment by 0x4007** [comment]
Same problem I had all day the other day when working on the plugin, so maybe I broke something environment related on the production deployment somehow by making a new cloudflare account.

**Comment by gentlementlegen** [comment]
It appears to me that the logic to decode the schema is wrong, and this would be introduced by Jordan's PR addition regarding the configuration accepting the amount of parallel tasks allowed for each user. If not provided, the default configuration fails which is why it is failing in your last try, on ubiquity / ubiquibot orgs, but not on mine where I provide the full config. Working on a fix right now.

**Comment by 0x4007** [comment]
You should start by reverting his pull, reopening the issue, and then take your time with the fix

**Comment by cohow** [comment]
Completed just waiting on code review.
